---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: alertmanager-ingress-basic-auth
spec:
  type: kv-v2
  mount: kvv2
  path: kube-prometheus-stack/alertmanager-ingress-basic-auth
  destination:
    name: alertmanager-ingress-basic-auth
    create: true
  vaultAuthRef: alertmanager
