---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: minio
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: minio
    # TODO: operator will only create the sa after the secret is already in place
    # so let's use default for now
    serviceAccount: default
